### ISSUE TITLE
The code works fine but there is an error in the Index.html. Can you figure it out ?

### ISSUE THREAD

**Issue by Grace-Hephzibah** [Grace-Hephzibah/HelloWorld#1]
The code is working fine. But there is a minor error in the code. Fixing it will be really helpful.

**Comment by namruthahari** [comment]
Can you assign this task to me?

**Comment by Grace-Hephzibah** [comment]
I have assigned the task to you .

**Comment by namruthahari** [comment]
I have rectified the error in code of index.html file and created a pull request.

**Comment by Grace-Hephzibah** [comment]
Success
